repos:
  - repo: https://github.com/psf/black
    rev: 21.12b0
    hooks:
      - id: black
  - repo: https://github.com/pycqa/isort
    rev: 5.10.1
    hooks:
      - id: isort
        name: isort (python)
  - repo: https://github.com/pycqa/flake8
    rev: "8c1ed24738ca6ed0fa8a76f8890d104e63878323"
    hooks:
      - id: flake8
  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: "f6f816c65d285f8a4a15e0e9965b3dd66ecddd79"
    hooks:
      - id: mypy
